// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCex1_tCBBHHFsuR1lEy-8DsdM1juHZZw',
    appId: '1:436723406:web:edbd2324ae05ecb8d83a9f',
    messagingSenderId: '436723406',
    projectId: 'healthpilot-89733',
    authDomain: 'healthpilot-89733.firebaseapp.com',
    storageBucket: 'healthpilot-89733.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOlynsXTs2twh1sX-3Kd0gxGO1YEz2nRI',
    appId: '1:436723406:android:6c1d72695d3d7227d83a9f',
    messagingSenderId: '436723406',
    projectId: 'healthpilot-89733',
    storageBucket: 'healthpilot-89733.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzzd2sK_1tvJPwQnRvA_gw8Js1cxZxPJI',
    appId: '1:436723406:ios:5be693ef93493a9fd83a9f',
    messagingSenderId: '436723406',
    projectId: 'healthpilot-89733',
    storageBucket: 'healthpilot-89733.firebasestorage.app',
    iosBundleId: 'com.example.healthpilot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzzd2sK_1tvJPwQnRvA_gw8Js1cxZxPJI',
    appId: '1:436723406:ios:5be693ef93493a9fd83a9f',
    messagingSenderId: '436723406',
    projectId: 'healthpilot-89733',
    storageBucket: 'healthpilot-89733.firebasestorage.app',
    iosBundleId: 'com.example.healthpilot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCex1_tCBBHHFsuR1lEy-8DsdM1juHZZw',
    appId: '1:436723406:web:61daebd6574fc034d83a9f',
    messagingSenderId: '436723406',
    projectId: 'healthpilot-89733',
    authDomain: 'healthpilot-89733.firebaseapp.com',
    storageBucket: 'healthpilot-89733.firebasestorage.app',
  );
}
